import java.nio.file.Files

for (def sourceSet in [
			sourceSets.main,
			sourceSets.client
		]) {
	// We have to capture the source set name for the lazy string literals,
	// otherwise it'll just be whatever the last source set is in the list.
	def sourceSetName = sourceSet.name
	tasks.register("generate%sPackageInfos".formatted(sourceSetName.capitalize()), GeneratePackageInfos) {
		group = 'fabric'
		description = "Generates package-info files for $sourceSetName packages."

		// Only apply to default source directory since we also add the generated
		// sources to the source set.
		sourceRoot = file("src/$sourceSetName/java")
		header = rootProject.file('HEADER')
	}

	def checkTask = tasks.register("check%sPackageInfos".formatted(sourceSetName.capitalize()), CheckPackageInfos) {
		description = "Checks that all $sourceSetName packages have @NullMarked package-info files."
		sourceRoot = file("src/$sourceSetName/java")
	}
	tasks.check.dependsOn checkTask
}

abstract class GeneratePackageInfos extends DefaultTask {
	@InputFile
	File header

	@Input
	abstract Property<String> getProjectName()

	@SkipWhenEmpty
	@InputDirectory
	final DirectoryProperty sourceRoot = project.objects.directoryProperty()

	GeneratePackageInfos() {
		projectName.set(project.name)
	}

	@TaskAction
	def run() {
		def headerText = header.readLines().join("\n") // normalize line endings
		def root = sourceRoot.get().asFile.toPath()

		root.eachDirRecurse {
			def containsJava = Files.list(it).any {
				Files.isRegularFile(it) && it.fileName.toString().endsWith('.java')
			}

			if (!containsJava) {
				return
			}

			// Check existing package-info.java to ensure it has @NullMarked
			def existingPackageInfo = it.resolve('package-info.java')
			if (Files.exists(existingPackageInfo)) {
				if (!existingPackageInfo.text.contains("@NullMarked")) {
					throw new RuntimeException("package-info.java ${existingPackageInfo} is missing @NullMarked annotation.")
				}

				return
			}

			def relativePath = root.relativize(it)
			def packageName = relativePath.toString().replace(File.separator, '.')

			if (packageName == "net.fabricmc.fabric.api.util" && projectName.get() == "fabric-content-registries-v0") {
				// Hack: This package clashes with api-base, don't generate any annotations for it.
				return
			}

			def implPattern = /^(net[\/\\]fabricmc[\/\\]fabric[\/\\](impl|mixin))/
			def isImpl = relativePath.toString() =~ implPattern

			it.resolve('package-info.java').withWriter {
				if (isImpl) {
					it.write("""$headerText
						|/**
						| * Implementation code for ${projectName.get()}.
						| */
						|@ApiStatus.Internal
						|@NullMarked
						|package $packageName;
						|
						|import org.jetbrains.annotations.ApiStatus;
						|import org.jspecify.annotations.NullMarked;
						|""".stripMargin())
				} else {
					it.write("""$headerText
						|/**
						| * API code for ${projectName.get()}.
						| */
						|@NullMarked
						|package $packageName;
						|
						|import org.jspecify.annotations.NullMarked;
						|""".stripMargin())
				}
			}
		}
	}
}

abstract class CheckPackageInfos extends DefaultTask {
	@Input
	abstract Property<String> getProjectName()

	@SkipWhenEmpty
	@InputDirectory
	final DirectoryProperty sourceRoot = project.objects.directoryProperty()

	CheckPackageInfos() {
		projectName.set(project.name)
	}

	@TaskAction
	def run() {
		def root = sourceRoot.get().asFile.toPath()
		def errors = []

		root.eachDirRecurse {
			def containsJava = Files.list(it).any {
				Files.isRegularFile(it) && it.fileName.toString().endsWith('.java')
			}

			if (!containsJava) {
				return
			}

			def relativePath = root.relativize(it)
			def packageName = relativePath.toString().replace(File.separator, '.')

			if (packageName == "net.fabricmc.fabric.api.util" && projectName.get() == "fabric-content-registries-v0") {
				// Hack: This package clashes with api-base, so no annotations are generated for it.
				return
			}

			def implPattern = /^(net[\/\\]fabricmc[\/\\]fabric[\/\\](impl|mixin))/
			def isImpl = relativePath.toString() =~ implPattern

			def existingPackageInfo = it.resolve('package-info.java')
			if (!Files.exists(existingPackageInfo)) {
				errors << "Missing package-info.java in package: " + packageName
				return
			} else if (!existingPackageInfo.text.contains("@NullMarked")) {
				errors << "package-info.java ${existingPackageInfo} is missing @NullMarked annotation."
				return
			} else if (isImpl && !existingPackageInfo.text.contains("@ApiStatus.Internal")) {
				errors << "Impl package-info.java ${existingPackageInfo} is missing @ApiStatus.Internal annotation."
				return
			}
		}

		if (!errors.isEmpty()) {
			throw new GradleException("Package info check failed:\n" + errors.join("\n"))
		}
	}
}
