plugins {
	id 'groovy-gradle-plugin'
	id 'checkstyle'
	id "com.diffplug.spotless" version "6.20.0"
}

repositories {
	maven {
		name = 'Fabric'
		url = 'https://maven.fabricmc.net/'
	}
	gradlePluginPortal()
	mavenCentral()
}

dependencies {
	implementation "net.fabricmc:fabric-loom:1.17.0-alpha.19"
}

checkstyle {
	configFile = file("../checkstyle.xml")
	toolVersion = "10.20.2"
}

spotless {
	lineEndings = com.diffplug.spotless.LineEnding.UNIX

	java {
		licenseHeaderFile(file("../HEADER"))
		removeUnusedImports()
		importOrder('java', 'javax', '', 'net.minecraft', 'net.fabricmc')
		indentWithTabs()
		trimTrailingWhitespace()
	}
}
