plugins {
	id 'groovy-gradle-plugin'
	id 'checkstyle'
	alias(libs.plugins.spotless)
}

repositories {
	maven {
		name = 'Fabric'
		url = 'https://maven.fabricmc.net/'
	}
	gradlePluginPortal()
	mavenCentral()
}

dependencies {
	implementation libs.fabric.loom
}

checkstyle {
	configFile = file("../checkstyle.xml")
	toolVersion = libs.versions.checkstyle.get()
}

spotless {
	lineEndings = com.diffplug.spotless.LineEnding.UNIX

	java {
		licenseHeaderFile(file("../HEADER"))
		removeUnusedImports()
		importOrder('java', 'javax', '', 'net.minecraft', 'net.fabricmc')
		indentWithTabs()
		trimTrailingWhitespace()
	}
}
