import net.fabricmc.fabric.impl.build.FabricApiBuildUtils

plugins {
	id "fabric-api.testing"
}

def includedModuleProjects = rootProject.allprojects.findAll {
	FabricApiBuildUtils.isFabricModule(it) && it != project
}

def nestedTestModJars = project.files()

for (def moduleProject : includedModuleProjects) {
	def currentModuleProject = moduleProject
	currentModuleProject.afterEvaluate {
		if (currentModuleProject.file("src/testmod").exists() || currentModuleProject.file("src/testmodClient").exists()) {
			nestedTestModJars.from(currentModuleProject.tasks.named("testmodJar"))
		}

		loom.mods.register(currentModuleProject.name) {
			sourceSet currentModuleProject.sourceSets.main
			sourceSet currentModuleProject.sourceSets.client
		}

		loom.mods.register(currentModuleProject.name + "-testmod") {
			sourceSet currentModuleProject.sourceSets.testmod
			sourceSet currentModuleProject.sourceSets.testmodClient
		}

		dependencies {
			testmodImplementation currentModuleProject.sourceSets.testmod.output
			testmodClientImplementation currentModuleProject.sourceSets.testmodClient.output
		}
	}
}

loom {
	runs {
		gametest {
			inherit testmodServer
			name "Game Test"
			vmArg "-Dfabric-api.gametest"
			vmArg "-Dfabric-api.gametest.report-file=${project.layout.buildDirectory.file("junit.xml").get().getAsFile()}"
			runDir "build/gametest"
			source sourceSets.testmod
		}
		autoTestServer {
			inherit testmodServer
			name "Auto Test Server"
			vmArg "-Dfabric.autoTest"
			source sourceSets.testmod
		}
		clientGametest {
			inherit testmodClient
			name "Client Game Test"
			vmArg "-Dfabric.client.gametest"
			vmArg "-Dfabric-tag-conventions-v2.missingTagTranslationWarning=fail"
			vmArg "-Dfabric-tag-conventions-v1.legacyTagWarning=fail"
			source sourceSets.testmodClient
		}
	}
}

runGametest {
	outputs.file project.layout.buildDirectory.file("junit.xml")
}

loom.nestJars(tasks.named("testmodJar"), nestedTestModJars)
